language: objective-c
osx_image: xcode9.2
cache:
  directories:
  - Carthage
before_install:
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet
script:
  - fastlane test
notifications:
  slack: openfoodfacts:Pw0UOEvADDxNN90ugITF7PKC
env:
  global:
    secure: TzLeh5qKxmFNlP/LpwsBPdjmXu7UpyKIe6SQdHDQm/bQ9+fSu89Lp8Db9dTPyWXEgKcC3i5X0TeaRcEzvYBk3eZdevd3Axx6dA+xM31FRtGVmZdJ62tUZbQsLNHJo5lAe+K6gQBfiJd983s2goEwrNHNnRaGrmv7xSPPJW4DCeCFW9S/jC0cRCcSZwdrmR986DjnIr7aTiWaSd+XMms60rmBCb7jZbCxYAOPU64uOqRdc0Og2mi8q1XHZzWi7b2OkAdpOwrWzcd4K2XTxfbEIbfhOkAg9bZ2h3+z7VMpWcUYwV7aIOo4ra2u/QkzNK6jZ4Q3h3TLK0e4ilj6vNCWsCqYScDU/BzgZCfhenWcD75Zz5CO0rdAlyQ3gMaxvIsntEyiCpUknYi+i1lMfH/mFwnb323qYdIXJ/BEBLnycqZqZksl43DUoKjmxMElNKKJ8g+TKp+M7FXKBKCd/zPejycLsq4/Z50OKPHPa+q7SLoo1Iryir5IRlD9uZ1EWQq2II2ACUZRuf0gA6GUm7aZEJNWk8QrunI0G75TlKmu9l7gsie5NVMcqZeETfU3vIxuFKJtbV/k2Viw/sQ6h2pr4hUf/VRrfzZCAljTs7ZgKP1sweMRGgU/U2T/Kw2/wB7no8eZ9KdrEcxe1xid0yKyTIWBkeP+7Yvjcu2y2GtYao0=
